name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build and run
        run: |
          docker compose up -d --build
          sleep 10
          curl -f http://localhost:8080/health
          curl -f http://localhost:4000/health
      - name: Down
        if: always()
        run: docker compose down -v

